package Monopoly;


import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;



@Controller    // This means that this class is a Controller
@RequestMapping(path="/jugadores") // This means URL's start with /demo (after Application path)
public class JugadoresController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private JugadoresRepository jugadoresRepository;
	@Autowired
private PropiedadesRepository propiedadesRepository;

	@GetMapping(path="/pagarLloguer")
	public @ResponseBody boolean pagarLloguer(@RequestParam int idJ, @RequestParam int idP) {
		Optional<Jugadores> oj = jugadoresRepository.findById(idJ);
		Jugadores j = oj.get();
		Optional<Propiedades> op = propiedadesRepository.findById(idP);
		Propiedades p = op.get();
		int apagar = p.getAlquiler();
		if (j.getDinero() >= apagar) {
			System.out.print(j.getDinero() + " - ");
			modificarDiners(j.getId(),-apagar);
			System.out.print(apagar + " = ");
			System.out.println(j.getDinero());	
			modificarDiners(p.getPropietario().getId(),apagar);
			return true;
		}
		else {
			return false;
		}
	}
	
	@GetMapping(path="/pagarLloguer")
	public @ResponseBody void modificarDiners(@RequestParam int idJ, @RequestParam int i) {
		Optional<Jugadores> oj = jugadoresRepository.findById(idJ);
		Jugadores j = oj.get();
		j.setDinero(j.getDinero() + i);
	}
	
}
